-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Värd: 127.0.0.1
-- Tid vid skapande: 06 maj 2026 kl 13:38
-- Serverversion: 10.4.32-MariaDB
-- PHP-version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Databas: `league_of_legends`
--

-- --------------------------------------------------------

--
-- Tabellstruktur `item`
--

CREATE TABLE `item` (
  `ID` int(11) NOT NULL,
  `name` varchar(99) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `item-group` varchar(99) DEFAULT NULL,
  `ability` varchar(999) DEFAULT NULL,
  `image` varchar(99) DEFAULT NULL,
  `health` int(11) DEFAULT NULL,
  `health-regen` int(11) DEFAULT NULL,
  `heal-and-shield-power` int(11) DEFAULT NULL,
  `armor` int(11) DEFAULT NULL,
  `magic-resistance` int(11) DEFAULT NULL,
  `tenacity` int(11) DEFAULT NULL,
  `slow-resist` int(11) DEFAULT NULL,
  `attack-speed` int(11) DEFAULT NULL,
  `attack-damage` int(11) DEFAULT NULL,
  `ability-power` int(11) DEFAULT NULL,
  `crit-chance` int(11) DEFAULT NULL,
  `crit-damage` int(11) DEFAULT NULL,
  `lethality` int(11) DEFAULT NULL,
  `magic-pen` int(11) DEFAULT NULL,
  `life-steal` int(11) DEFAULT NULL,
  `omnivamp` int(11) DEFAULT NULL,
  `gold-generation` int(11) DEFAULT NULL,
  `ability-haste` int(11) DEFAULT NULL,
  `mana` int(11) DEFAULT NULL,
  `mana-regen` int(11) DEFAULT NULL,
  `movement-speed` int(11) DEFAULT NULL,
  `movement-speed-percent` int(11) DEFAULT NULL,
  `armor-pen-percent` int(11) DEFAULT NULL,
  `magic-pen-percent` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Dumpning av Data i tabell `item`
--

INSERT INTO `item` (`ID`, `name`, `cost`, `item-group`, `ability`, `image`, `health`, `health-regen`, `heal-and-shield-power`, `armor`, `magic-resistance`, `tenacity`, `slow-resist`, `attack-speed`, `attack-damage`, `ability-power`, `crit-chance`, `crit-damage`, `lethality`, `magic-pen`, `life-steal`, `omnivamp`, `gold-generation`, `ability-haste`, `mana`, `mana-regen`, `movement-speed`, `movement-speed-percent`, `armor-pen-percent`, `magic-pen-percent`) VALUES
(4, 'Blade of the Ruined King', 3200, NULL, 'Unique – Mist\'s Edge: Basic attacks deal bonus physical damage on-hit equal to (Melee role 8% / Ranged role 5%) of the target\'s current health, with a maximum of 100 against Minion icon minions and Monster icon monsters.\r\nUnique – Clawing Shadows: Basic attacks on-hit against enemy champions apply a stack for 6 seconds, stacking up to 3 times. The third stack consumes them all to Slow icon slow the target by 30% for 1 second (15 second cooldown).', 'Blade_of_the_Ruined_King_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, 40, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, 'Void Staff', 3000, 'BLIGHT', NULL, 'Void_Staff_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 95, NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 'Infinity Edge', 3600, NULL, NULL, 'Infinity_Edge_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 70, NULL, 25, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7, 'Berserker\'s Greaves', 1100, 'BOOTS', NULL, 'Berserkers_Greaves_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL),
(11, 'Boots of Swiftness', 1000, 'BOOTS', 'Unique – Fleetfooted: Gain 25% slow resist', 'Boots_of_Swiftness_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL),
(12, 'Ionian Boots of Lucidity', 900, 'BOOTS', 'Unique – Ionian Insight: Gain 10 summoner spell haste', 'Ionian_Boots_of_Lucidity_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, 45, NULL, NULL, NULL),
(13, 'Mercury\'s Treads', 1300, 'BOOTS', NULL, 'Mercurys_Treads_item_HD.webp', NULL, NULL, NULL, NULL, 20, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL),
(14, 'Plated Steelcaps', 1200, 'BOOTS', 'Unique – Plating: Reduces incoming damage from all basic attacks by 12% (excluding turret attacks).', 'Plated_Steelcaps_item_HD.webp', NULL, NULL, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL),
(15, 'Sorcerer\'s Shoes', 1100, 'BOOTS', NULL, 'Sorcerers_Shoes_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL),
(16, 'Symbiotic Soles', 900, 'BOOTS', 'Unique – Voidborn: Gain Empowered Recall Empowered Recall.\r\nUnique – Symbiosis: After moving a total of 150,000 units of distance, capped at 500 units at a time for Dash dashes and Flash blinks, upgrade this item to Synchronized Souls Synchronized Souls.', 'Symbiotic_Soles_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL, NULL, NULL),
(17, 'Synchronized Souls', 900, 'BOOTS', 'Unique – Voidborn: Gain Empowered Recall Empowered Recall.\r\nUnique – Synchrony: Gain 45 bonus movement speed while out-of-combat.', 'Synchronized_Souls_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL),
(19, 'Abyssal Mask', 2650, 'BLIGHT', 'Unique – Unmake: Enemy champions within 700 units of you become cursed, reducing their magic resistance by 30%.', 'Abyssal_Mask_item_HD.webp', 300, NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'Archangel\'s Staff', 2900, 'MANAFLOW, LIFELINE', 'Unique – Awe: Grants ability power equal to 1% bonus mana.\r\nUnique – Manaflow: Grants a charge every 8 seconds, up to 5 charges. Affecting an enemy or ally with an ability consumes a charge to grant 5 bonus mana, increased to 10 if they are a champion, up to a maximum of 360 bonus mana.\r\nTransforms into Seraph\'s Embrace Seraph\'s Embrace at 360 bonus mana.', 'Archangels_Staff_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 70, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, 600, NULL, NULL, NULL, NULL, NULL),
(21, 'Ardent Censer', 2200, NULL, 'Unique – Sanctify: Heal power icon Healing or Hybrid resistances icon shielding allied champions (excluding yourself) enhances you and them for 6 seconds, granting 25% bonus attack speed and 20 bonus magic damage on-hit on basic attacks.', 'Ardent_Censer_item_HD.webp', NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 125, NULL, 4, NULL, NULL),
(22, 'Axiom Arc', 3000, NULL, 'Unique – Flux: Scoring a Damage rating takedown against an enemy champion within 3 seconds of damaging them refunds 15% (+ 0.15% per 1 Lethality) of your ultimate ability\'s total cooldown.', 'Axiom_Arc_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 55, NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL, 20, NULL, NULL, NULL, NULL, NULL, NULL),
(23, 'Banshee\'s Veil', 3000, 'ANNUL', 'Unique – Annul: Grants a Sivir Spell Shield spell shield that blocks the next hostile ability (40 (restarts upon taking damage from champions) second cooldown).', 'Banshees_Veil_item_HD.webp', NULL, NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, 105, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(24, 'Black Cleaver', 3000, 'FATALITY', 'Unique – Carve: Dealing physical damage to an enemy champion applies a stack of Carve for 6 seconds, stacking up to 5 times. Each stack inflicts 6% armor reduction, up to 30% at 5 stacks.\r\nUnique – Fervor: Dealing physical damage grants you 20 bonus movement speed for 2 seconds.', 'Black_Cleaver_item_HD.webp', 400, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, NULL, NULL, NULL, NULL, NULL, NULL),
(25, 'Blackfire Torch', 2800, NULL, 'Unique – Baleful Blaze: Dealing ability damage burns enemies, causing them to take 10 (+ 1% AP) magic damage every 0.5 seconds over 3 seconds, for a total of 60 (+ 6% AP). Against monsters, the burn deals 10 bonus magic damage per tick, dealing a total of 20 (+ 1% AP) magic damage per tick for up to 120 (+ 6% AP).\r\nUnique – Blackfire: For each champion, epic monster, and large monster afflicted with Baleful Blaze\'s burn, increase your ability power by 4%.', 'Blackfire_Torch_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 80, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, 600, NULL, NULL, NULL, NULL, NULL),
(26, 'Bloodletter\'s Curse', 2900, 'BLIGHT', 'Unique – Vile Decay: Dealing magic damage with abilities or passives to champions reduces their Magic Resistance by 5% for 6 seconds, up to 30%.', 'Bloodletters_Veil_item.webp', 350, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(27, 'Bloodsong', 400, 'SUPPORT, JUNGLE, SPELLBLADE', 'Unique – Ward: Consumes a charge to place a Stealth Ward icon Stealth Ward at the target location, which grants Sight icon sight of the surrounding area. Charges refill upon visiting the shop (4 charges; 600 range).\r\nUnique – Spellblade: After using an ability, your next basic attack within 10 seconds deals 100% base AD bonus physical damage on-hit. If the target is a champion, inflict them with Expose Weakness for 6 seconds, causing them to take (Melee role 10% / Ranged role 5%) increased damage from all sources (1.5 (begins after using the empowered attack) second cooldown).\r\nUnique: Receives diminishing gold from excessive minion kills.', 'Bloodsong_item_HD.webp', 200, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, 75, NULL, NULL, NULL, NULL),
(28, 'Bloodthirster', 3400, NULL, 'Unique – Ichorshield: Convert the Heal power icon healing received from Life steal icon life steal in excess of maximum health into a Hybrid resistances icon shield for up to 165 − 315 (based on level), which lasts until destroyed.', 'Bloodthirster_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 80, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(29, 'Bounty of Worlds', 400, 'SUPPORT, JUNGLE', 'Unique – Ward: Consumes a charge to place a Stealth Ward icon Stealth Ward at the target location, which grants Sight icon sight of the surrounding area. Charges refill upon visiting the shop (4 charges; 600 range).\r\nUnique – Upgrade: You have completed the support quest and can now upgrade this item, Bounty of Worlds, for free into Bloodsong Bloodsong, Celestial Opposition Celestial Opposition, Dream Maker Dream Maker, Solstice Sleigh Solstice Sleigh, or Zaz\'Zak\'s Realmspike Zaz\'Zak\'s Realmspike by selecting one of them from a custom menu in the HUD or the shop. The upgrade can be done outside the shop using the menu.\r\nUnique: Receives diminishing gold from excessive minion kills.', 'Bounty_of_Worlds_item_HD.webp', 200, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, 75, NULL, NULL, NULL, NULL),
(31, 'Celestial Opposition', 400, 'SUPPORT, JUNGLE', 'Unique – Ward: Consumes a charge to place a Stealth Ward icon Stealth Ward at the target location, which grants Sight icon sight of the surrounding area. Charges refill upon visiting the shop (4 charges; 600 range). Unique – Blessing of the Mountain: Become Blessed to reduce incoming champion damage by (Melee role 35% / Ranged role 25%), lingering for 2 seconds after taking damage from a champion. After the linger ends, you lose Blessed to unleash a shockwave around you that Slow icon slows nearby enemies by 50% for 1.5 seconds (18 (restarts upon taking damage from champions) second cooldown). Unique: Receives diminishing gold from excessive minion kills.', 'Celestial_Opposition_item_HD.webp', 200, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, 75, NULL, NULL, NULL, NULL),
(32, 'Chempunk Chainsword', 3100, NULL, 'Unique – Hackshorn: Dealing physical damage to enemy champions inflicts them with Grievous Wounds icon Grievous Wounds for 3 seconds.', 'Chempunk_Chainsword_item_HD.webp', 450, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(33, 'Cosmic Drive', 3000, NULL, 'Unique – Spelldance: Dealing magic or true damage to an enemy champion grants you 20 bonus movement speed for 4 seconds.', 'Cosmic_Drive_item_HD.webp', 350, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 70, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, NULL, NULL, NULL, 4, NULL, NULL),
(34, 'Cryptbloom', 2850, 'BLIGHT', 'Unique – Life From Death: Scoring a Damage rating takedown against an enemy champion while alive and within 3 seconds of damaging them summons a nova that radiates from the location of their death over 1.75 seconds, Heal power icon healing you and allied champions hit for 100 (+ 25% AP) (60 second cooldown).', 'Cryptbloom_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, 30),
(35, 'Dawncore', 2500, NULL, 'Unique – First Light: Gain 2% heal and shield power and 10 ability power for every additional 100% base mana regeneration.', 'Dawncore_item_HD.webp', NULL, NULL, 16, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
(36, 'Dead Man\'s Plate', 2900, 'MOMENTUM', 'Unique – Shipwrecker: While moving, generates 7 stacks of Momentum every 0.25 seconds, granting up to 20 bonus movement speed at 100 stacks after 3.75 seconds of moving. Basic attacks consume all stacks to deal 0 − 40 (based on Momentum) (+ 0% − 100% (based on Momentum) base AD) bonus physical damage on-hit. Unique – Unsinkable: Gain 25% Slow immune icon slow resist.', 'Dead_Mans_Plate_item_HD.webp', 350, NULL, NULL, 55, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(37, 'Death\'s Dance', 3300, NULL, 'Unique – Ignore Pain: Reduces (Melee role 30% / Ranged role 10%) of all post-mitigation physical and magic damage received and instead stores the damage to successively take it as true damage over 3 seconds, dealing a third of the stored damage each second. Unique – Defy: If an enemy champion dies within 3 seconds of you damaging them, removes Ignore Pain\'s remaining stored damage and Heal power icon heals you for 75% bonus AD over 2 seconds.', 'Deaths_Dance_item_HD.webp', NULL, NULL, NULL, 50, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(38, 'Dream Maker', 400, 'SUPPORT, JUNGLE', 'Unique – Ward: Consumes a charge to place a Stealth Ward icon Stealth Ward at the target location, which grants Sight icon sight of the surrounding area. Charges refill upon visiting the shop (4 charges; 600 range).  Unique – Dream Maker: Every 8 seconds, you gain a Blue Dream Bubble and a Purple Dream Bubble. Granting a Heal power icon heal or Hybrid resistances icon shield to an allied champion (excluding yourself) causes you to blow both of your Dream Bubbles to them, empowering them for 3 seconds. The Blue Bubble reduces the next instance of non-Minion icon minion damage they take by 75 − 255 (based on your level) and the Purple Bubble grants them 50 − 170 (based on your level) bonus magic damage on-hit on their next basic attack. Unique: Receives diminishing gold from excessive minion kills.', 'Dream_Maker_item_HD.webp', 200, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, 75, NULL, NULL, NULL, NULL),
(39, 'Echoes of Helia', 2200, NULL, 'Unique – Soul Siphon: Damaging an enemy champion with a basic attack or ability damage grants a Soul Shard, up to 2. Heal power icon Healing or Hybrid resistances icon shielding an allied champion (excluding yourself) consumes all Soul Shards to heal them for 65 per shard and deal 50 magic damage per shard to the nearest enemy champion within 1100 units of the ally.', 'Echoes_of_Helia_item_HD.webp', 200, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, NULL, 125, NULL, NULL, NULL, NULL),
(40, 'Eclipse', 2900, NULL, 'Unique – Ever Rising Moon: Damaging basic attacks, abilities, item effects, and summoner spells, as well as the application of Stun icon crowd control and damage over time effects, generate stacks against enemy champions, up to one per attack or cast per champion. Applying 2 stacks to a champion within a 2 second period deals bonus physical damage to them equal to (Melee role 6% / Ranged role 4%) of target\'s maximum health and grants you a Hybrid resistances icon shield for (Melee role 160 / Ranged role 80) (+ (Melee role 40% / Ranged role 20%) bonus AD) for 2 seconds (6 second cooldown).', 'Eclipse_item.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(41, 'Edge of Night', 3000, 'ANNUL', 'Unique – Annul: Grants a Sivir Spell Shield spell shield that blocks the next hostile ability (40 (restarts upon taking damage from champions) second cooldown).', 'Edge_of_Night_item_HD.webp', 250, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(42, 'Essence Reaver', 2900, NULL, 'Unique – Essence Drain: Basic attacks on-hit restore 15 (+ 10% bonus AD) mana.', 'Essence_Reaver_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(43, 'Experimental Hexplate', 3000, NULL, 'Unique – Hexcharged: Gain 30 ultimate haste. Unique – Overdrive: Upon casting your ultimate ability, enter Overdrive to gain 30% bonus attack speed and 15% bonus movement speed for 8 seconds (30 (starts on ultimate cast) second cooldown).', 'Experimental_Hexplate_item_HD.webp', 450, NULL, NULL, NULL, NULL, NULL, NULL, 20, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(44, 'Fimbulwinter', 2400, 'MANAFLOW', 'Unique – Awe: Grants bonus health equal to 15% bonus mana. Unique – Everlasting: Stun icon Immobilizing, or Slow icon slowing if you are Melee role melee, an enemy champion grants a 100 − 180 (based on level) (+ 4.5% current mana) Hybrid resistances icon shield for 3 seconds (8 second cooldown). The shield\'s strength is increased「 by 80% 」if there is more than one enemy champion within Range center 1200 units.', 'Fimbulwinter_item_HD.webp', 550, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 860, NULL, NULL, NULL, NULL, NULL),
(45, 'Force of Nature', 2800, NULL, 'Unique – Steadfast: Taking magic damage from champions grants a stack of Steadfast for 7 seconds, stacking up to 8 times with the duration refreshing on subsequent magic damage from them and whenever dealing damage to them. Becoming Stun icon immobilized by an enemy champion grants 2 stacks and also refreshes the duration. Damaging basic attacks and spells per cast instance can only grant 1 stack of Steadfast every 1 second. At maximum stacks, gain 70 bonus magic resistance and 6% bonus movement speed.', 'Force_of_Nature_item_HD.webp', 400, NULL, NULL, NULL, 55, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(46, 'Frozen Heart', 2500, NULL, 'Unique – Winter\'s Caress: Cripple icon Cripples the attack speed of enemy champions within 700 units by 20%.', 'Frozen_Heart_item_HD.webp', NULL, NULL, NULL, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, 400, NULL, NULL, NULL, NULL, NULL),
(47, 'Guardian Angel', 3200, NULL, 'Unique – Rebirth: Upon taking lethal damage, enter Revival icon resurrection for 4 seconds, during which you are Taric Cosmic Radiance invulnerable, Untargetable icon untargetable, and unable to act, and afterwards Heal power icon heal for 50% of base health and restore 100% of maximum mana (300 (starts after resurrecting) second cooldown).', 'Guardian_Angel_item_HD.webp', NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, 55, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(48, 'Guinsoo\'s Rageblade', 3000, NULL, 'Unique – Wrath: Basic attacks deal 30 bonus magic damage on-hit. Unique – Seething Strike: Basic attacks grant 8% bonus attack speed for 3 seconds, stacking up to 4 times for a total of 32% bonus attack speed. At maximum stacks, basic attacks on-attack also grant a Phantom stack for 6 seconds, up to 2 stacks. At 2 Phantom stacks, the next basic attack consumes all of those stacks on-attack to trigger a Phantom Hit that applies On-hit icon on-hit effects to the target at 100% effectiveness after a 0.15 second delay.', 'Guinsoos_Rageblade_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, 30, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(49, 'Heartsteel', 3000, NULL, 'Unique – Colossal Consumption: While within 700 units of an enemy champion, generate a stack on them each second, stacking up to 3 times. Your next basic attack against a target with 3 stacks is empowered to consume them all to deal 70 (+ 6% max health) bonus physical damage on-hit and grant you permanent bonus health equal to「 8% of that amount 」bonus health from items) 」 (30 (per target) second cooldown). Unique – Goliath: Gain 0% − 30% (based on maximum health) increased size.', 'Heartsteel_item_HD.webp', 900, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50, 'Hextech Rocketbelt', 2600, NULL, 'Unique – Supersonic: Dash Dash 125 to 275 units in the target direction, though not through terrain, unleashing an arc of 7 rockets in the same direction that deal 100 (+ 10% AP) magic damage to enemies hit (40 second cooldown). Supersonic resets the user\'s basic attack timer.', 'Hextech_Rocketbelt_item_HD.webp', 350, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(51, 'Hollow Radiance', 2800, 'IMMOLATE', 'Unique – Immolate: Taking or dealing damage activates this passive for 3 seconds. Deal 15 (+ 1% bonus health) magic damage every second to enemies within Range center 325 (+ 100% bonus size) units, with the damage being increased by 25% against Minion icon minions and Monster icon monsters. This executes minions that would be killed by one more tick of damage. Unique – Desolate: Killing an enemy unit deals 30 (+ 2% bonus health) magic damage to enemies near them.', 'Hollow_Radiance_item_HD.webp', 400, 100, NULL, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(52, 'Horizon Focus', 2700, NULL, 'Unique – Hypershot: Dealing ability damage to a champion at Range center 600 or more units away from the cast position Reveal icon reveals them and increases your damage dealt to them by 10% for 6 seconds. Unique – Focus: Upon triggering Hypershot, grant Sight icon sight of the area Range center 1400 units around the target and apply Hypershot\'s effects to enemy champions within the area for 3 seconds (30 second cooldown).', 'Horizon_Focus_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL),
(53, 'Hubris', 3000, NULL, 'Unique – Eminence: Scoring a Damage rating takedown against an enemy champion within 3 seconds of damaging them generates a permanent stack and grants you 15 (+ 2 per stack) bonus attack damage for 90 seconds.', 'Hubris_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(54, 'Hullbreaker', 3000, NULL, 'Unique – Skipper: Basic attacks on-hit against any enemy grant a stack for 10 seconds, stacking up to 5 times. At maximum stacks, or 4 stacks, your next basic attack against a champion, epic monster, or structure consumes all stacks to deal (Melee role 120% / Ranged role 84%) base AD (+ (Melee role 5% / Ranged role 3.5%) maximum health) bonus physical damage, increased to (Melee role 300% / Ranged role 210%) base AD (+ (Melee role 10% / Ranged role 7%) maximum health) against structures. Unique – Boarding Party: Allied siege minions siege minions and super minions super minions within Range model 1050 units gain (Melee role 70 − 130 / Ranged role 35 − 65) (based on level) bonus armor and bonus magic re', 'Hullbreaker_item_HD.webp', 500, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(55, 'Iceborn Gauntlet', 2900, 'SPELLBLADE', 'Unique – Spellblade: After using an ability, your next basic attack within 10 seconds deals 150% base AD bonus physical damage on-hit and creates a 300 radius frost field for 2 seconds. Enemies within the field are slowed by (Melee role 25% / Ranged role 12.5%) (1.5 (begins after using the empowered attack) second cooldown).', 'Iceborn_Gauntlet_item_HD.webp', 300, NULL, NULL, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(56, 'Immortal Shieldbow', 3000, 'LIFELINE', 'Unique – Lifeline: If you would take damage that would reduce you below 30% of your maximum health, you first gain a Hybrid resistances icon shield that absorbs (Melee role 400 − 700 / Ranged role 320 − 560) (based on level) damage for 3 seconds (90 second cooldown).', 'Immortal_Shieldbow_item.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 55, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(57, 'Imperial Mandate', 2250, NULL, 'Unique – Coordinated Fire: Abilities that Slow icon slow or Stun icon immobilize enemy champions mark them for 5 seconds. Allied champions that damage marked enemies consume the mark to deal 10% of the target\'s current health bonus magic damage (9 (per target, starts upon mark application) second cooldown).', 'Imperial_Mandate_item.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, NULL, 125, NULL, NULL, NULL, NULL),
(58, 'Jak\'Sho, The Protean', 3200, NULL, 'Unique – Voidborn Resilience: Gain a stack for each second in combat with enemy champions, stacking up to 5 times. At maximum stacks, increase your bonus armor and bonus magic resistance by 30% until the end of combat.', 'JakSho_The_Protean_item_HD.webp', 350, NULL, NULL, 45, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(59, 'Kaenic Rookern', 2900, NULL, 'Unique – Magebane: After not taking magic damage for 15 seconds, gain a Hybrid resistances icon shield that absorbs magic damage equal to 15% of maximum health until destroyed.', 'Kaenic_Rookern_item_HD.webp', 400, 100, NULL, NULL, 80, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(60, 'Knight\'s Vow', 2300, NULL, 'Unique – Pledge: Designate the target allied champion as being Worthy, forming a Karma Focused Resolve tether between you and them. Champions can only be designated as Worthy by one Knight\'s Vow at a time. You cannot be designated as Worthy by an ally\'s Knight\'s Vow (60 second cooldown; Range center 1250 range).  Unique – Sacrifice: While your Worthy ally is tethered to you and you are above 30% of your maximum health, redirect 12% of the pre-mitigation physical and magic damage they take to you as the respective damage type. Additionally, you Heal power icon heal for 10% of the post-mitigation damage dealt by your Worthy ally to champions.', 'Knights_Vow_item_HD.webp', 200, 100, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(61, 'Kraken Slayer', 3100, NULL, 'Unique – Bring It Down: Basic attacks on-hit grant a stack for 3 seconds, up to 2 stacks. At 2 stacks, the next basic attack consumes all stacks to deal (Melee role 150 − 200 / Ranged role 120 − 160) (based on level) bonus physical damage on-hit, increased by 0% − 50% (based on target\'s missing health), for up to (Melee role 225 − 300 / Ranged role 180 − 240) (based on level) bonus physical damage.', 'Kraken_Slayer_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(62, 'Liandry\'s Torment', 3000, NULL, 'Unique – Torment: Dealing ability damage burns enemies, causing them to take「 2% of the target\'s maximum health magic damage every 1 seconds over 3 seconds, capped at 40 per seconds against monsters. 」 Unique – Suffering: For each second in combat with enemy champions, deal 2% increased damage, stacking up to 3 times for a total of 6%.', 'Liandrys_Torment_item_HD.webp', 300, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 70, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(63, 'Lich Bane', 3200, 'SPELLBLADE', 'Unique – Spellblade: After using an ability, your next basic attack within 10 seconds gains 50% bonus attack speed and deals 75% base AD (+ 40% AP) bonus magic damage on-hit (1.5 (begins after using the empowered attack) second cooldown).', 'Lich_Bane_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 115, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, 4, NULL, NULL),
(64, 'Locket of the Iron Solari', 2200, NULL, 'Unique – Devotion: Grants you and allied champions within Range center 850 units a Hybrid resistances icon shield for 200 − 360 (based on target\'s level) that decays over 2.5 seconds (90 second cooldown).', 'Locket_of_the_Iron_Solari_item_HD.webp', 200, NULL, NULL, 25, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(65, 'Lord Dominik\'s Regards', 3000, 'FATALITY', NULL, 'Lord_Dominiks_Regards_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL),
(66, 'Luden\'s Companion', 2850, NULL, 'Unique – Fire: Gain 6 Shot Charge stacks to fire. Dealing ability damage to an enemy consumes all Shot Charges to deal 75 (+ 5% AP) bonus magic damage to them and, for each charge consumed beyond the first, an additional enemy within Range center 600 units of them, firing an orb at each secondary target that impacts after 0.528 seconds to deal the damage. If the number of additional targets fired at is less than the number of charges consumed,「 deal an additional 15 − 75 (based on remaining Shot Charges) (+ 1% − 5% AP) magic damage to the primary target, for a total of 90 − 150 (+ 6% − 10% AP). 」 (12 second cooldown).', 'Ludens_Companion_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 600, NULL, NULL, NULL, NULL, NULL),
(67, 'Malignance', 2700, NULL, 'Unique – Scorn: Gain 20 ultimate haste. Unique – Hatefog: Dealing ability damage to enemy champions with your ultimate ability creates a 251 − 550 (based on ultimate\'s damage instance) radius scorched zone beneath them for 3 seconds, applying a Curse to enemies within that deals 「 15 (+ 1.25% AP) magic damage every 0.25 seconds 」 and reduces their magic resistance by 10 (3 (per target, starts on zone creation) second cooldown).', 'Malignance_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 85, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 600, NULL, NULL, NULL, NULL, NULL),
(68, 'Manamune', 2900, 'MANAFLOW', 'Unique – Awe: Grants bonus attack damage equal to 2% maximum mana. Unique – Manaflow: Grants a charge every 8 seconds, up to 4 charges. Consumes a charge on-hit and whenever affecting an enemy or ally with an ability to grant 3 bonus mana, increased to 6 for champion targets, up to a maximum of 360 bonus mana. Transforms into Muramana Muramana at 360 bonus mana.', 'Manamune_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 500, NULL, NULL, NULL, NULL, NULL),
(69, 'Maw of Malmortius', 3100, 'LIFELINE', 'Unique – Lifeline: If you would take magic damage that would reduce you below 30% of your maximum health, you first gain a Hybrid resistances icon shield that absorbs (Melee role 200 / Ranged role 150) (+ (Melee role 150% / Ranged role 112.5%) bonus AD) magic damage for 3 seconds. Additionally, triggering this effect grants you 10% omnivamp until the end of combat (90 second cooldown).', 'Maw_of_Malmortius_item_HD.webp', NULL, NULL, NULL, NULL, 40, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(70, 'Mejai\'s Soulstealer', 1500, 'GLORY', 'Unique – Glory: Gain 4 stacks for each champion kill and 2 stacks for each assist, up to a maximum of 25 stacks. For every stack, gain 5 ability power, up to 125 at maximum stacks. If you have at least 10 stacks, also gain 10% bonus movement speed. Lose 10 stacks on death. Stacks are preserved from Dark Seal Dark Seal.', 'Mejais_Soulstealer_item_HD.webp', 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(71, 'Mercurial Scimitar', 3200, 'QUICKSILVER', 'Unique – Quicksilver: Removes all Stun icon crowd control debuffs (except Airborne icon Airborne) from your champion and grants 50% bonus total movement speed and Ghost ghosting for 1.5 seconds (90 second cooldown).', 'Mercurial_Scimitar_item_HD.webp', NULL, NULL, NULL, NULL, 40, NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(72, 'Mikael\'s Blessing', 2300, NULL, 'Unique – Purify: Remove all Stun icon crowd control debuffs (except Airborne icon Airborne, Blind icon Blind, Disarm icon Disarm, Nearsight icon Nearsight, and Suppression icon Suppression) from yourself or the target allied champion and Heal power icon heal the target for 100 − 250 (based on target\'s level) (120 second cooldown; Range center 650 range).', 'Mikaels_Blessing_item_HD.webp', 250, NULL, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, NULL),
(73, 'Moonstone Renewer', 2200, NULL, 'Unique – Starlit Grace: Heal power icon Healing or Hybrid resistances icon shielding an allied champion chains the effect to the other nearest allied champion within Range center 800 units of them (excluding yourself), granting them 30% of the heal or 35% of the shield\'s initial strength. If no other allied champions are in the radius, grant the same target an additional 30% of the heal or 35% of the shield.', 'Moonstone_Renewer_item_HD.webp', 200, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, NULL, 125, NULL, NULL, NULL, NULL),
(74, 'Morellonomicon', 2950, NULL, 'Unique – Grievous Wounds: Dealing magic damage to enemy champions inflicts them with Grievous Wounds icon Grievous Wounds for 3 seconds.', 'Morellonomicon_item_HD.webp', 350, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(75, 'Mortal Reminder', 3200, 'FATALITY', 'Unique – Grievous Wounds: Dealing physical damage to enemy champions inflicts them with Grievous Wounds icon Grievous Wounds for 3 seconds.', 'Mortal_Reminder_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30, NULL),
(76, 'Muramana', 2900, 'MANAFLOW', 'Unique – Awe: Grants bonus attack damage equal to 2% maximum mana. Unique – Shock: Basic attacks on-hit against champions deal 1.2% maximum mana bonus physical damage. Dealing ability damage to champions deals (Melee role 4% / Ranged role 3%) maximum mana bonus physical damage. Can only be triggered on the same target once every 6.5 seconds from the same attack or cast.', 'Muramana_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 860, NULL, NULL, NULL, NULL, NULL),
(77, 'Nashor\'s Tooth', 3000, NULL, 'Unique – Icathian Bite: Basic attacks deal 15 (+ 15% AP) bonus magic damage on-hit.', 'Nashors_Tooth_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, NULL, 80, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(78, 'Navori Flickerblade', 2650, NULL, 'Unique – Transcendence: Basic attacks on-attack reduce the remaining cooldowns of your basic abilities by 15%.', 'Navori_Flickerblade_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL),
(79, 'Opportunity', 2700, NULL, 'Unique – Preparation: After being out-of-combat with enemy champions for 8 seconds, gain (Melee role 11 / Ranged role 7) lethality. This bonus remains for 3 seconds after dealing damage to an enemy champion. Unique – Extraction: Scoring a Damage rating takedown against an enemy champion within 3 seconds of damaging them grants you 200 bonus movement speed that decays over 1.5 seconds.', 'Opportunity_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 55, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(80, 'Overlord\'s Bloodmail', 3300, NULL, 'Unique – Tyranny: Gain bonus attack damage equal to 2% bonus health. Unique – Retribution: Gain 0% − 10% (based on missing health) bonus attack damage.', 'Overlords_Bloodmail_item_HD.webp', 550, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(81, 'Phantom Dancer', 2650, NULL, 'Unique – Spectral Waltz: Become permanently Ghost ghosted.', 'Phantom_Dancer_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, NULL, NULL),
(82, 'Profane Hydra', 3200, 'HYDRA', 'Unique – Heretical Cleave: Deal 80% AD physical damage to enemies in a Range center 450 radius (10 second cooldown).  Unique – Cleave: Damaging basic attacks deal (Melee role 40% AD / Ranged role 20% AD) physical damage to other enemies in a Range center 350 radius centered around the target.', 'Profane_Hydra_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(83, 'Rabadon\'s Deathcap', 3600, NULL, 'Unique – Magical Opus: Increase your ability power by 30%.', 'Rabadons_Deathcap_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 130, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(84, 'Randuin\'s Omen', 2700, NULL, 'Unique – Humility: Unleash a shockwave around you that Slow icon slows nearby enemies by 70% for 2 seconds (90 second cooldown; Range center 500 range).  Unique – Critical Resilience: Reduces incoming damage from Critical strike icon critical strikes by 30%.', 'Randuins_Omen_item_HD.webp', 350, NULL, NULL, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(85, 'Rapid Firecannon', 2650, NULL, 'Unique – Energized: Moving and basic attacking generates Energize stacks, up to 100. Unique – Sharpshooter: When fully Kircheis Shard item Energized, your next basic attack deals 40 bonus magic damage on-hit. Energized attacks gain 35% bonus range, capped at 150.', 'Rapid_Firecannon_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(86, 'Ravenous Hydra', 3300, 'HYDRA', 'Unique – Ravenous Crescent: Deal 80% AD physical damage to enemies within a Range center 450 radius in front of you (10 second cooldown).  Unique – Cleave: Basic attacks on-hit deal (Melee role 40% AD / Ranged role 20% AD) physical damage to other enemies in a Range center 350 radius centered around the target.', 'Ravenous_Hydra_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 65, NULL, NULL, NULL, NULL, NULL, 12, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(87, 'Redemption', 2300, NULL, 'Unique – Intervention: Call upon a beam of light to strike upon the target location after 2.5 seconds, granting Sight icon sight of the area for the duration. Allies within the area are Heal power icon healed for 200 − 400 (based on target\'s level), while enemy champions within take 10% of target\'s maximum health as true damage. Can be used while dead. (90 second cooldown; 5500 range).', 'Redemption_item_HD.webp', 200, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, 100, NULL, NULL, NULL, NULL),
(88, 'Riftmaker', 3100, NULL, 'Unique – Void Corruption: For each second in combat with champions, deal 2% increased damage, stacking up to 4 times for a total of 8% increased damage. At maximum stacks, gain (Melee role 10% / Ranged role 6%) omnivamp. Unique – Void Infusion: Gain ability power equal to 2% bonus health.', 'Riftmaker_item_HD.webp', 350, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 70, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(89, 'Rod of Ages', 2600, 'ETERNITY', 'Unique – Timeless: This item gains 10 bonus health, 20 bonus mana, and 3 ability power every minute, up to 10 times, for a maximum of 100 bonus health, 200 bonus mana, and 30 ability power. Upon reaching maximum stacks, gain a level that preserves your current experience (cap remains at level 18). Unique – Eternity: Restore mana equal to 10% of pre-mitigation damage taken from champions, and Heal power icon heal for an amount equal to 25% of mana spent, up to 20 per cast. Toggled abilities can only heal for up to 20 per second.', 'Rod_of_Ages_item_HD.webp', 350, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 400, NULL, NULL, NULL, NULL, NULL),
(90, 'Runaan\'s Hurricane', 2650, NULL, 'Unique – Wind\'s Fury: Basic attacks on-attack fire additional bolts at up to 2 enemies in front of you, each dealing 55% AD physical damage. Bolts apply On-hit icon on-hit effects at 100% effectiveness and are affected by Critical strike icon critical strike modifiers. The bolts will target the closest enemies to you that are not the main target.', 'Runaans_Hurricane_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, NULL, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(91, 'Rylai\'s Crystal Scepter', 2600, NULL, 'Unique – Rimefrost: Dealing ability damage Slow icon slows affected units by 30% for 1 second.', 'Rylais_Crystal_Scepter_item_HD.webp', 400, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 65, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(92, 'Seraph\'s Embrace', 2900, 'MANAFLOW, LIFELINE', 'Unique – Awe: Grants ability power equal to 2% bonus mana. Unique – Lifeline: If you would take damage that would reduce you below 30% of your maximum health, you first gain a Hybrid resistances icon shield that absorbs 200 (+ 20% current mana) damage for 3 seconds (90 second cooldown).', 'Seraphs_Embrace_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 70, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, 1000, NULL, NULL, NULL, NULL, NULL),
(93, 'Serpent\'s Fang', 2500, NULL, 'Unique – Shield Reaver: Dealing damage to an enemy champion inflicts them with venom for 3 seconds, reducing any Hybrid resistances icon shields they gain within the duration by (Melee role 50% / Ranged role 35%), and if the target was not already afflicted by the venom, reducing all of their active shields by the same amount.', 'Serpents_Fang_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 55, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(94, 'Shadowflame', 3200, NULL, 'Unique – Cinderbloom: Magic and true damage Critical strike icon critically strike against enemies below 40% maximum health for 120% damage.', 'Shadowflame_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 110, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(95, 'Shurelya\'s Battlesong', 2200, NULL, 'Unique – Inspiring Speech: Grants you and all allies within 1000 units 30% bonus movement speed for 4 seconds (75 second cooldown).', 'Shurelyas_Battlesong_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, 125, NULL, 4, NULL, NULL),
(96, 'Solstice Sleigh', 400, 'SUPPORT, JUNGLE', 'Unique – Ward: Consumes a charge to place a Stealth Ward icon Stealth Ward at the target location, which grants Sight icon sight of the surrounding area. Charges refill upon visiting the shop (4 charges; 600 range).  Unique – Going Sledding: Slow icon Slowing or Stun icon immobilizing an enemy champion causes you and the nearest and most wounded allied champion to gain 20% bonus movement speed decaying over 2.5 seconds, and 50 − 230 (based on your level) bonus health for 2.5 seconds. This bonus may exceed maximum health (30 second cooldown). Unique: Receives diminishing gold from excessive minion kills.', 'Solstice_Sleigh_item_HD.webp', 200, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, 75, NULL, NULL, NULL, NULL),
(97, 'Spear of Shojin', 3100, NULL, 'Unique – Dragonforce: Gain 25 basic ability haste. Unique – Focused Will: Dealing ability damage with a champion ability grants a stack for 6 seconds, stacking up to 4 times and up to 1 per cast instance per second and every second for damage over time abilities. For each stack, your ability damage and proc damage dealt by abilities gain 3% increased damage, for a total increase of 12% at maximum stacks.', 'Spear_of_Shojin_item_HD.webp', 450, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(98, 'Spirit Visage', 2700, NULL, 'Unique – Boundless Vitality: Increases all Heal power icon healing and Hybrid resistances icon shielding received as well as Health regeneration icon health regeneration by 25%.', 'Spirit_Visage_item_HD.webp', 400, 100, NULL, NULL, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(99, 'Staff of Flowing Water', 2250, NULL, 'Unique – Rapids: Heal power icon Healing or Hybrid resistances icon shielding allied champions (excluding yourself) grants you and them 45 ability power for 4 seconds.', 'Staff_of_Flowing_Water_item_HD.webp', NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, 35, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, 125, NULL, NULL, NULL, NULL),
(100, 'Statikk Shiv', 2700, NULL, 'Unique – Electrospark: Your first 3 attacks within 8 seconds fire chain lightning on-hit, hitting up to 5 targets (including the attack target) for 60 magic damage, increased to 85 for minions/monsters (25-10s CD levels 7-12) (25-10 second cooldown). Unique – Electroshock: Scoring a Damage rating takedown within 3 seconds resets the cooldown on ElectrosparkScoring.', 'Statikk_Shiv_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(101, 'Sterak\'s Gage', 3200, 'LIFELINE', 'Unique – The Claws that Catch: Gain bonus attack damage equal to 45% base AD. Unique – Lifeline: If you would take damage that would reduce you below 30% of your maximum health, you first gain a Hybrid resistances icon shield that absorbs damage equal to 60% of bonus health which decays over 4.5 seconds (90 second cooldown).', 'Steraks_Gage_item_HD.webp', 400, NULL, NULL, NULL, NULL, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(102, 'Stormsurge', 2900, NULL, 'Unique – Stormraider: Dealing damage to an enemy champion equal to 25% of their maximum health within 2.5 seconds inflicts them with Squall and grants you 25% bonus movement speed for 1.5 seconds (30 (starts on application) second cooldown). Unique – Squall: After 2 seconds of having applied Squall, strike the target with lightning, dealing 125 (+ 10% AP) magic damage to them. If the target dies before being struck, they emit an electric field instantly that shocks all enemy champions near them, dealing them the same damage and granting you 30 Gold 30.', 'Stormsurge_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 90, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(103, 'Stridebreaker', 3300, 'HYDRA', 'Unique – Breaking Shockwave: Deal 80% AD physical damage to enemies in a Range center 450 radius centered around you and Slow icon slow them by 35% for 3 seconds. For each champion hit, gain 35% bonus movement speed decaying over 3 seconds. Can move while casting (15 second cooldown).  Unique – Cleave: Basic attacks on-hit deal (Melee role 40% AD / Ranged role 20% AD) physical damage to other enemies in a Range center 350 radius centered around the target.', 'Stridebreaker_item_HD.webp', 450, NULL, NULL, NULL, NULL, NULL, NULL, 25, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(104, 'Sundered Sky', 3100, NULL, 'Unique – Lightshield Strike: Your next basic attack against a champion is empowered to Critical strike icon critically strike for 175% damage and Heal power icon heal you for (Melee role 100% / Ranged role 50%) base AD (+ 6% of your missing health). Excess healing beyond maximum health is converted to bonus health for 8 seconds (8 (per target) second cooldown).', 'Sundered_Sky_item_HD.webp', 400, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(105, 'Sunfire Aegis', 2700, 'IMMOLATE', 'Unique – Immolate: Taking or dealing damage activates this passive for 3 seconds. Deal 20 (+ 1% bonus health) magic damage every second to enemies within Range center 325 (+ 100% bonus size) units, with the damage being increased by 50% against Minion icon minions and Monster icon monsters. This executes minions that would be killed by one more tick of damage.', 'Sunfire_Aegis_item_HD.webp', 350, NULL, NULL, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `item` (`ID`, `name`, `cost`, `item-group`, `ability`, `image`, `health`, `health-regen`, `heal-and-shield-power`, `armor`, `magic-resistance`, `tenacity`, `slow-resist`, `attack-speed`, `attack-damage`, `ability-power`, `crit-chance`, `crit-damage`, `lethality`, `magic-pen`, `life-steal`, `omnivamp`, `gold-generation`, `ability-haste`, `mana`, `mana-regen`, `movement-speed`, `movement-speed-percent`, `armor-pen-percent`, `magic-pen-percent`) VALUES
(106, 'Terminus', 3000, 'FATALITY, BLIGHT', 'Unique – Shadow: Basic attacks deal 30 bonus magic damage on-hit. Unique – Juxtaposition: Basic attacks On-hit icon on-hit against champions alternate between Light and Dark hits, each one granting a bonus for 5 seconds that stacks up to 3 times. Light hits grant 6 / 7 / 8 (based on level) bonus armor and bonus magic resistance while Dark hits grant 10% armor penetration and magic penetration, for a total of 18 − 24 (based on level) bonus resistances and 30% resistances penetration at maximum stacks of each.', 'Terminus_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(107, 'The Collector', 3000, NULL, 'Unique – Death: If you deal post-mitigation damage that would leave a champion below 5% of their maximum health, Pyke Death from Below execute them. Unique – Taxes: Killing a champion grants you an additional 25 Gold 25.', 'The_Collector_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, NULL, 25, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(108, 'Thornmail', 2450, NULL, 'Unique – Thorns: When struck by a basic attack on-hit, deal 20 (+ 10% bonus armor) magic damage to the attacker and, if they are a champion, inflict them with Grievous Wounds icon Grievous Wounds for 3 seconds.', 'Thornmail_item_HD.webp', 150, NULL, NULL, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(109, 'Titanic Hydra', 3300, 'HYDRA', 'Unique – Titanic Crescent: Your next basic attack within 10 seconds empowers Cleave to deal (Melee role 4% / Ranged role 2%) maximum health bonus physical damage to the primary target and (Melee role 9% / Ranged role 4.5%) maximum health physical damage to secondary targets (10 (begins after using the empowered attack) second cooldown). Titanic Crescent resets the user\'s basic attack timer.  Unique – Cleave: Basic attacks on-hit deal (Melee role 1% / Ranged role 0.5%) maximum health bonus physical damage to the target and (Melee role 3% / Ranged role 1.5%) maximum health physical damage to other enemies in a cone in the direction of the primary target.', 'Titanic_Hydra_item_HD.webp', 600, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(110, 'Trailblazer', 2400, 'MOMENTUM', 'Unique – Lead the Way: While moving, generate 7 stacks of Momentum every 0.25 seconds, granting up to 20 bonus movement speed at 100 stacks after 3.75 seconds of moving. At maximum stacks, you leave behind a path briefly that grants 15% of your total movement speed as bonus movement speed to allied champions within. Basic attacks consume all stacks. If you are Melee role melee and at maximum stacks, your next basic attack Slow icon slows the target by 50% for 1 second.', 'Trailblazer_item_HD.webp', 250, NULL, NULL, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(111, 'Trinity Force', 3333, 'SPELLBLADE', 'Unique – Spellblade: After using an ability, your next basic attack within 10 seconds deals 200% base AD bonus physical damage on-hit (1.5 (begins after using the empowered attack) second cooldown). Unique – Quicken: Basic attacks on-hit grant 20 bonus movement speed for 2 seconds', 'Trinity_Force_item_HD.webp', 333, NULL, NULL, NULL, NULL, NULL, NULL, 30, 36, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL),
(112, 'Umbral Glaive', 2600, NULL, 'Unique – Blackout: When near an enemy stealthed Ward icon ward or Teemo Noxious Trap trap, gain Blackout for 8 seconds (50 second cooldown; 400 range). Blackout: You Disabled Ward icon disable surrounding stealthed wards, as well as Exposed icon expose and True Sight icon reveal nearby stealthed wards and traps while Blackout is active. Unique: Your basic attacks deal (Melee role 2 / Ranged role 1) bonus true damage to wards.', 'Umbral_Glaive_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(113, 'Unending Despair', 2800, NULL, 'Unique – Anguish: Every 5 seconds in combat with champions, deal 30 − 50 (based on level) (+ 3% bonus health) magic damage to enemy champions within 650 units and Heal power icon heal yourself equal to 250% of the post-mitigation damage dealt to all targets.', 'Unending_Despair_item_HD.webp', 400, NULL, NULL, 25, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(114, 'Vigilant Wardstone', 2300, 'SIGHTSTONE', 'Unique – Arcane Cache: This item can store up to 3 purchased Control Wards Control Wards. Unique – Behold: Increase your Stealth Ward icon Stealth Ward, Totem Ward icon Totem Ward, and Control Ward icon Control Ward caps by 1.', 'Vigilant_Wardstone_item_HD.webp', 250, NULL, NULL, 25, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, NULL, NULL, NULL, NULL, NULL, NULL),
(115, 'Voltaic Cyclosword', 3000, NULL, 'Unique – Energized: Moving and basic attacking generates Energize stacks, up to 100. Unique – Galvanize: Kircheis Shard item Energized stack generation is increased by 75% for distance travelled from Dash dashes and Flash blinks, as well as while moving in Teemo Guerrilla Warfare stealth. Unique – Firmament: When fully Kircheis Shard item Energized, your next basic attack deals 100 bonus physical damage on-hit and Slow icon slows the target by (Melee role 99% / Ranged role 20%) for 0.75 seconds.', 'Voltaic_Cyclosword_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 55, NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(116, 'Warmog\'s Armor', 3300, NULL, 'Unique: Grants Warmog\'s Heart if you have at least 1500 bonus health. Unique – Warmog\'s Heart: Health regeneration icon Regenerate「 2.5% maximum health every 0.5 seconds 」and gain 4% bonus movement speed if damage has not been taken in the last 6 seconds (3 seconds for damage from non-champions).', 'Warmogs_Armor_item_HD.webp', 1000, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(117, 'Winter\'s Approach', 2400, 'MANAFLOW', 'Unique – Awe: Grants bonus health equal to 15% bonus mana. Unique – Manaflow: Grants a charge every 8 seconds, up to 4 charges. Consumes a charge on-hit and whenever affecting an enemy or ally with an ability to grant 3 bonus mana, increased to 6 for champion targets, up to a maximum of 360 bonus mana. Transforms into Fimbulwinter Fimbulwinter at 360 bonus mana.', 'Winters_Approach_item_HD.webp', 550, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, 500, NULL, NULL, NULL, NULL, NULL),
(118, 'Wit\'s End', 2800, NULL, 'Unique – Fray: Basic attacks deal 45 bonus magic damage on-hit.', 'Wits_End_item_HD.webp', NULL, NULL, NULL, NULL, 45, 20, NULL, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(119, 'Youmuu\'s Ghostblade', 2800, NULL, 'Unique – Wraith Step: Gain (Melee role 20% / Ranged role 15%) bonus movement speed and Ghost ghosting for (Melee role 6 / Ranged role 4) seconds (45 second cooldown).  Unique – Haunt: Gain (Melee role 20 / Ranged role 10) bonus movement speed while out-of-combat.', 'Youmuus_Ghostblade_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 55, NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL),
(120, 'Yun Tal Wildarrows', 3000, NULL, 'Unique – Practice Makes Lethal: on-attack gain +Critical strike icon 0.2% permanently up to 25% Unique – Flurry: on-attacking an enemy champion, gain 30% bonus attack speed for 6 seconds. Attacks reduce this cooldown by 1 second, increased to 2 seconds with Critical strike icon critical strikes (30 second cooldown).', 'Yun_Tal_Wildarrows_item_HD.webp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 35, 55, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(121, 'Zaz\'Zak\'s Realmspike', 400, 'SUPPORT, JUNGLE', 'Unique – Ward: Consumes a charge to place a Stealth Ward icon Stealth Ward at the target location, which grants Sight icon sight of the surrounding area. Charges refill upon visiting the shop (4 charges; 600 range).  Unique – Void Explosion: Dealing ability damage to an enemy champion creates an explosion at their location after a 0.5-second delay, dealing 10 (+ 20% AP) (+ 3% of each target\'s maximum health) magic damage to enemies within the area, capped at 300 against Monster icon monsters (10 second cooldown). Unique: Receives diminishing gold from excessive minion kills.', 'Zazs_Realmspike_item_HD.webp', 200, 75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, 75, NULL, NULL, NULL, NULL),
(122, 'Zeke\'s Convergence', 2300, NULL, 'Unique – Frostfire Tempest: Upon casting your ultimate ability, you summon a storm of flame and ice around you for 5 seconds, dealing「 7.5 magic damage every 0.25 seconds 」to nearby enemies and Slow icon slowing them by 30% (45 (starts on ultimate cast) second cooldown).', 'Zekes_Convergence_item_HD.webp', 300, NULL, NULL, 25, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL),
(123, 'Zhonya\'s Hourglass', 3250, 'STASIS', 'Unique – Time Stop: Put yourself in Stasis icon stasis for 2.5 seconds, rendering you Untargetable icon untargetable and Taric Cosmic Radiance invulnerable for the duration but also unable to move, declare basic attacks, cast abilities, use summoner spells, or activate items (120 second cooldown).', 'Zhonyas_Hourglass_item_HD.webp', NULL, NULL, NULL, 50, NULL, NULL, NULL, NULL, NULL, 105, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- --------------------------------------------------------

--
-- Tabellstruktur `user`
--

CREATE TABLE `user` (
  `UUID` int(11) NOT NULL,
  `username` varchar(99) NOT NULL,
  `email` varchar(99) NOT NULL,
  `access-level` int(11) NOT NULL,
  `password` varchar(99) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Index för dumpade tabeller
--

--
-- Index för tabell `item`
--
ALTER TABLE `item`
  ADD PRIMARY KEY (`ID`);

--
-- Index för tabell `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`UUID`);

--
-- AUTO_INCREMENT för dumpade tabeller
--

--
-- AUTO_INCREMENT för tabell `item`
--
ALTER TABLE `item`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=124;

--
-- AUTO_INCREMENT för tabell `user`
--
ALTER TABLE `user`
  MODIFY `UUID` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
